{{- if and (.Values.podDisruptionBudgetEnabled) (gt (.Values.replicas | int64) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "golden-chart.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "golden-chart.selectorLabels" . | nindent 6 }}
{{- end }}