apiVersion: v1
kind: Secret
metadata:
  name: {{ include "golden-chart.fullname" . }}
  labels:
    {{- include "golden-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.properties.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
